# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  Contact: /contact

# Logo Image Source
logo_src: https://placehold.it/500x100
profile_pic: /images/profile-pic.jpg
# Theme Main Subtitle
subtitle_main: DevOps expert. Specialized in AWS, Docker and test automation.

# Theme Secondary subtitle
susbtitle_secondary: My Name is Maarten van den Ende. I help companies implement a digital strategy through consulting, audits, coaching and training. 

# Footer About Section
about_footer: Prospire is helps companies implement a digital strategy through consulting, audits, coaching and training.

# Default post title
default_post_title: blogpost

# Default post cover index page (Recommended)
default_cover_index: "https://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail: "https://placehold.it/1300x500"

# Show Dates for posts and pages
show_dates: true

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: propsire-nl
  # # Facebook comments
  # facebook:
  #   appid:
  #   comment_count: 5
  #   comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-112339-12

# Social Accounts
twitter_url: https://twitter.com/mjvdende
github_url: https://github.com/mjvdende
email_url: mailto:maartenvdende@gmail.com?subject=Mail from mjvdende.com
rss_url: /atom.xml
phone_url: +31635120295
skype_url: maartenjohn
whatsapp_url: +31635120295
linkedin_url: https://www.linkedin.com/in/mjvdende/
